### ISSUE TITLE
Running ChromDIff without expression data

### ISSUE THREAD

**Issue by dyndna** [angieyen/ChromDiff#1]
@angieyen: Thanks for sharing complete code. I read README and manuscript but haven't looked into detail of all analysis options and analysis flow. I wonder if chromdiff can be run without supplying expression matrix at step 4: `./perform_analysis.sh` in https://raw.githubusercontent.com/angieyen/ChromDiff/master/notes_v2.sh

Thanks,
Samir

Also, url at https://github.com/angieyen/ChromDiff/blob/master/README.txt#L25 gives error 404 as it is renamed. I was able to download example set file using following command:

```
cd /apps/ChromDiff/statecalls/core

wget -e robots=off -r -nH --cut-dirs=9 --no-parent --reject="index.html" -A "E***_15_coreMarks_mnemonics.bed.gz" http://www.broadinstitute.org/~anshul/projects/roadmap/chromhmmSegmentations/ChmmModels/coreMarks/parallel/set2/final/
```

**Comment by angieyen** [comment]
@dyndna Yes, ChromDiff can be run without an expression matrix. That only affects the relevant results, which specifically are points 2d and 3 as described in "Part 4: Finding results generated by ChromDiff" in the README.txt file.

The best way to do that would be to go ahead and comment out the relevant lines. You should only need to do this in two places.
1. Comment out the following line in perform_analysis.sh (by adding # to the beginning of the line) :
      Rscript calc_pvals_v2.R $property $a_label $b_label $test_type $correction $curr_label $metadatafile $genefile $covariate_mat_file $map_covariates_file $expfile $state_annotations_file $generegions_label
2. Comment out the following two lines in plot_sig_majority_args_v2.sh (by adding # to the beginning of the line):
        echo "Generating expression heatmap..."
        Rscript mk_exp_heatmap.R $metric $testtype $correction $property $group1 $group2 $label1 $label2 ${model} $plottype $metadatafile $genefile $covariate_mat_file $map_covariates_file $expfile $state_annotations_file $generegions_label

If you try it, can you let me know how it goes? We could make a branch with these changes for people who would like to use ChromDiff without gene expression information, if everything works as expected.

**Comment by dyndna** [comment]
Thanks Angie and I will let you know how it goes.

**Comment by angieyen** [comment]
@dyndna Thank you for letting me know about the README error. You have correctly found the updated path, and I will update the README file to reflect the change. More generally, you can find the states I used here, in the "core 15-state model": http://egg2.wustl.edu/roadmap/web_portal/chr_state_learning.html#core_15state

**Comment by angieyen** [comment]
@dyndna The README file is updated in the master branch! Thanks again for pointing that out.
